
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JohnMayorga18
 */
public class PanelVista extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PanelVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        espacio0 = new javax.swing.JTextField();
        espacio1 = new javax.swing.JTextField();
        espacio2 = new javax.swing.JTextField();
        espacio3 = new javax.swing.JTextField();
        espacio4 = new javax.swing.JTextField();
        espacio5 = new javax.swing.JTextField();
        espacio6 = new javax.swing.JTextField();
        espacio7 = new javax.swing.JTextField();
        espacio8 = new javax.swing.JTextField();
        espacio9 = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnCalculos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        titulo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        titulo.setText("Operaciones Basicas con Arreglos:");

        espacio0.setMargin(new java.awt.Insets(0, 0, 0, 0));

        espacio1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        espacio2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        espacio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacio2ActionPerformed(evt);
            }
        });

        espacio3.setMargin(new java.awt.Insets(2, 2, 2, 2));

        espacio4.setMargin(new java.awt.Insets(2, 2, 2, 2));

        espacio5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        espacio5.setPreferredSize(new java.awt.Dimension(64, 22));

        espacio6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        espacio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacio6ActionPerformed(evt);
            }
        });

        espacio7.setMargin(new java.awt.Insets(0, 0, 0, 0));

        espacio8.setMargin(new java.awt.Insets(0, 0, 0, 0));

        espacio9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        espacio9.setPreferredSize(new java.awt.Dimension(64, 22));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 153));
        btnLimpiar.setText("Limpiar Arreglo:");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCalculos.setBackground(new java.awt.Color(153, 255, 153));
        btnCalculos.setText("Calculos Básicos:");
        btnCalculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculosActionPerformed(evt);
            }
        });

        lblResultado.setEditable(false);
        lblResultado.setBackground(new java.awt.Color(255, 204, 204));
        lblResultado.setColumns(20);
        lblResultado.setRows(5);
        jScrollPane1.setViewportView(lblResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(espacio0, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacio1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacio2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacio3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacio4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacio5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacio6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacio7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacio8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espacio9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(espacio0, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(espacio1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(espacio2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(espacio3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(espacio4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacio5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacio6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacio7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(espacio8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(espacio9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCalculos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculosActionPerformed
        
        //Declaro las variables
        float numArregloNumeros[] = new float[10]; //arreglo
        boolean esnumero=true;
        float totalSuma;
        float totalResta;
        float totalMultiplicacion;
        float totalPromedio;
        float totalDivision;
        
        //Convierto de Text (en la forma) a numero
        try {
            numArregloNumeros[0]=Float.parseFloat(espacio0.getText());    
        } catch (Exception e) {
            esnumero=false;
        }
        
        try {
            numArregloNumeros[1]=Float.parseFloat(espacio1.getText());
        } catch (Exception e) {
            esnumero=false;
        }
        
        try {
            numArregloNumeros[2]=Float.parseFloat(espacio2.getText());
        } catch (Exception e) {
            esnumero=false;
        }
        
        try {
            numArregloNumeros[3]=Float.parseFloat(espacio3.getText());
        } catch (Exception e) {
            esnumero=false;
        }
        
        try {
            numArregloNumeros[4]=Float.parseFloat(espacio4.getText());
        } catch (Exception e) {
            esnumero=false;
        }
        
        try {
            numArregloNumeros[5]=Float.parseFloat(espacio5.getText());
        } catch (Exception e) {
            esnumero=false;
        }
        
        try {
            numArregloNumeros[6]=Float.parseFloat(espacio6.getText());
        } catch (Exception e) {
            esnumero=false;
        }
        
        try {
            numArregloNumeros[7]=Float.parseFloat(espacio7.getText());    
        } catch (Exception e) {
            esnumero=false;
        }
        
        try {
            numArregloNumeros[8]=Float.parseFloat(espacio8.getText());
        } catch (Exception e) {
            esnumero=false;
        }
        
        try {
            numArregloNumeros[9]=Float.parseFloat(espacio9.getText());
        } catch (Exception e) {
            esnumero=false;
        }
        
        //Verifico si puedo Continuar
        if (esnumero) {
            
            //Procedo a hacer las operaciones simples
            totalSuma=(
                    numArregloNumeros[0]+numArregloNumeros[1]+numArregloNumeros[2]+
                    numArregloNumeros[3]+numArregloNumeros[4]+numArregloNumeros[5]+
                    numArregloNumeros[6]+numArregloNumeros[7]+numArregloNumeros[8]+
                    numArregloNumeros[9]
            );
            totalResta=(
                    numArregloNumeros[0]-numArregloNumeros[1]-numArregloNumeros[2]-
                    numArregloNumeros[3]-numArregloNumeros[4]-numArregloNumeros[5]-
                    numArregloNumeros[6]-numArregloNumeros[7]-numArregloNumeros[8]-
                    numArregloNumeros[9]
            );
            totalMultiplicacion=(
                    numArregloNumeros[0]*numArregloNumeros[1]*numArregloNumeros[2]*
                    numArregloNumeros[3]*numArregloNumeros[4]*numArregloNumeros[5]*
                    numArregloNumeros[6]*numArregloNumeros[7]*numArregloNumeros[8]*
                    numArregloNumeros[9]
            );
            totalPromedio=((
                    numArregloNumeros[0]+numArregloNumeros[1]+numArregloNumeros[2]+
                    numArregloNumeros[3]+numArregloNumeros[4]+numArregloNumeros[5]+
                    numArregloNumeros[6]+numArregloNumeros[7]+numArregloNumeros[8]+
                    numArregloNumeros[9]
            )/9);
            totalDivision=(
                    numArregloNumeros[0]/numArregloNumeros[1]/numArregloNumeros[2]/
                    numArregloNumeros[3]/numArregloNumeros[4]/numArregloNumeros[5]/
                    numArregloNumeros[6]/numArregloNumeros[7]/numArregloNumeros[8]/
                    numArregloNumeros[9]
            );
            
            //Procedo a mostrar los resultados
            lblResultado.setText("");
            lblResultado.setText(" Total Suma Arreglo de 9: " + totalSuma +
                                 "\n Total Resta Arreglo de 9: " + totalResta +
                                 "\n Total Multiplicación Arreglo de 9: " + totalMultiplicacion +
                                 "\n Total Promedio Arreglo de 9: " + totalPromedio +
                                 "\n Total Division Arreglo de 9: " + totalDivision
            );
            
            //Informo al Usuario
            JOptionPane.showMessageDialog(null,"Calculado Correctamente", "", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            JOptionPane.showMessageDialog(null, 
                            "No Puedes Agregar Texto, Espacios en Blanco "
                            + "u Caracteres Especiales a los Espacios del Arreglo. "
                            + "\n SOLO SE PERMITE NÚMEROS!!!!. ",
                    "Error Usuario: ", 
                    JOptionPane.ERROR_MESSAGE);
            
            espacio0.setText("");
            espacio1.setText("");
            espacio2.setText("");
            espacio3.setText("");
            espacio4.setText("");
            espacio5.setText("");
            espacio6.setText("");
            espacio7.setText("");
            espacio8.setText("");
            espacio9.setText("");
        }
    }//GEN-LAST:event_btnCalculosActionPerformed

    private void espacio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio2ActionPerformed

    private void espacio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacio6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espacio6ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        espacio0.setText("");
        espacio1.setText("");
        espacio2.setText("");
        espacio3.setText("");
        espacio4.setText("");
        espacio5.setText("");
        espacio6.setText("");
        espacio7.setText("");
        espacio8.setText("");
        espacio9.setText("");
        
        lblResultado.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JTextField espacio0;
    private javax.swing.JTextField espacio1;
    private javax.swing.JTextField espacio2;
    private javax.swing.JTextField espacio3;
    private javax.swing.JTextField espacio4;
    private javax.swing.JTextField espacio5;
    private javax.swing.JTextField espacio6;
    private javax.swing.JTextField espacio7;
    private javax.swing.JTextField espacio8;
    private javax.swing.JTextField espacio9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblResultado;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
